export { default as EnvelopeSvg } from "./svg/envelope";
export { default as LockSvg } from "./svg/lock";
export { default as SearchSvg } from "./svg/search";
export { default as LikeSvg } from "./svg/like";
export { default as PhotoSvg } from "./svg/photo";
export { default as MicroSvg } from "./svg/micro";
export { default as ImagesSvg } from "./svg/images";
export { default as TelegramSvg } from "./svg/telegram";
export { default as PlusSvg } from "./svg/plus";
